export const placements = [
  { name: 'Google', file: 'google.png' },
  { name: 'Microsoft', file: 'microsoft.png' },
  { name: 'Meta', file: 'meta.png' },
  { name: 'Amazon', file: 'amazon.png' },
  { name: 'Apple', file: 'apple.png' },
  { name: 'UBS', file: 'UBS.png' },
  { name: 'Wells Fargo', file: 'wells_fargo.png' },
  { name: 'Deutsche', file: 'deutsche.png' },
  { name: 'Datadog', file: 'datadog.png' },
  { name: 'Stripe', file: 'stripe.png' },
  { name: 'IBM', file: 'ibm.png' },
  { name: 'Protiviti', file: 'protiviti.png' },
  { name: 'Uber', file: 'uber.png' },
  { name: 'Duolingo', file: 'duolingo.png' },
  { name: 'Linkedin', file: 'linkedin.png' },
  { name: 'Doordash', file: 'doordash.png' },
  { name: 'PwC', file: 'pwc.png' },
  { name: 'Barclays', file: 'barclays.png' },
  { name: 'Medtronic', file: 'medtronic.png' },
  { name: 'Echo3D', file: 'echo3D.png' },
  { name: 'SLAC', file: 'SLAC.png' },
  { name: 'Jahnel Group', file: 'jahnel_group.png' },
  { name: 'Harvard Medical', file: 'harvard_medical.png' },
  { name: 'RTX', file: 'RTX.png' },
  { name: 'Regeneron', file: 'regeneron.png' },
  { name: 'CVTE', file: 'CVTE.png' },
  { name: 'Verizon', file: 'verizon.png' },
  { name: 'Goldman Sachs', file: 'goldman_sachs.png' },
  { name: 'Capital One', file: 'capital_one.png' },
  { name: 'EY', file: 'ey.png' },
  { name: 'Chicago Trading Company', file: 'chicago_trading.png' },
]

export const campusClubs = [
  { name: 'ACSU', file: 'acsu.png' },
  { name: 'ALFA', file: 'alfa.png' },
  { name: 'AppDev', file: 'appdev.png' },
  { name: 'Armada', file: 'armada.png' },
  { name: 'AUV', file: 'auv.png' },
  { name: 'Blockchain', file: 'blockchain.png' },
  { name: 'CDJ', file: 'cdj.png' },
  { name: 'CIBC', file: 'cibc.png' },
  { name: 'CDS', file: 'cds.png' },
  { name: 'CEV', file: 'cev.png' },
  { name: 'CHS', file: 'chs.png' },
  { name: 'CMR', file: 'cmr.png' },
  { name: 'CREDIT', file: 'credit.png' },
  { name: 'CTC', file: 'ctc.png' },
  { name: 'CUxD', file: 'cuxd.png' },
  { name: 'Cyber', file: 'cyber.png' },
  { name: 'DataStrat', file: 'datastrat.png' },
  { name: 'DCC', file: 'dcc.png' },
  { name: 'DTI', file: 'dti.png' },
  { name: 'Eship', file: 'eship.png' },
  { name: 'EWB', file: 'ewb.png' },
  { name: 'FinTech', file: 'fintech.png' },
  { name: 'Hack4Impact', file: 'hack4impact.png' },
  { name: 'IBC', file: 'ibc.png' },
  { name: 'IEEE', file: 'ieee.png' },
  { name: 'ISA', file: 'isa.png' },
  { name: 'Nexus', file: 'nexus.png' },
  { name: 'SWE', file: 'swe.png' },
  { name: 'Thread', file: 'thread.png' },
  { name: 'WebDev', file: 'webdev.png' },
  { name: 'WICC', file: 'wicc.png' },
]

export const galleryImages = [
  'images/gallery/2025PledgesKTP.JPEG',
  'images/gallery/IshaKatelyn.JPEG',
  'images/gallery/WonjinAmishiKatelyn.jpeg',
  'images/gallery/SaeshaLexi.JPEG',
  'images/gallery/gabesalanformal.JPEG',
  'images/gallery/biglilgirls.jpeg',
  'images/gallery/ktpdummies.jpeg',
  'images/gallery/founderHeart.JPEG',
  'images/gallery/2025dinner.jpeg',
  'images/gallery/cruisegroup.jpeg',
  'images/gallery/deeshlin.png',
  'images/gallery/betaaccept.png',
  'images/gallery/ktpmen.png',
  'images/gallery/jbhousewarming.png',
  'images/gallery/DeeshLexiHomecoming.JPEG',
  'images/gallery/deeshlils.png',
  'images/classpictures/2025eboard.JPG',
  'images/gallery/ktpatties.jpg',
]

export const KTP_CLASSES = ['Founders', 'Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta', 'Eta', 'Theta']
